[build]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh && composer self-update --snapshot"
  publish = "_site"
  environment = { PHP_VERSION = "7.2", CECIL_VERSION = "4.24.2", RUBY_VERSION = "2.6.2" }

[context.deploy-preview]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh $DEPLOY_PRIME_URL"


[[redirects]]
  from = "https://why000.netlify.com"
  to = "https://www.onlinemacizle.org"
  status = 301
  force = true
